version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minioV2
    ports:
      - "9005:9000"
      - "9006:9001"
    volumes:
      - ~/minioV2/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
    command: server --address :9000 --console-address :9001 /data
    restart: unless-stopped
